version: '3.7'

services:
  consul-node1:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - 'consul-node1_data:/bitnami'
    networks:
      mboa-network:
        aliases:
          - consul-net

  consul-node2:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    volumes:
      - 'consul-node2_data:/bitnami'
    networks:
      mboa-network:
        aliases:
          - consul2-net

  consul-node3:
    image: bitnami/consul
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
    volumes:
      - 'consul-node3_data:/bitnami'
    networks:
      mboa-network:
        aliases:
          - consul3-net

  account-api:
    image: eu.gcr.io/voltaic-cocoa-280715/account-repository
    environment:
      - spring.cloud.consul.host=consul-node1
      - spring.datasource.url=jdbc:postgresql://34.66.68.210:5432/mboaeat_db
      - spring.datasource.username=postgres
      - spring.datasource.password=Ee6mSPwjG85W
    networks:
      mboa-network:
          aliases:
            - account-api-net
      postgres-net:
          aliases:
            - postgres

  customer-api:
    image: eu.gcr.io/voltaic-cocoa-280715/customer-repository
    environment:
      - spring.cloud.consul.host=consul-node1
      - spring.datasource.url=jdbc:postgresql://34.66.68.210:5432/mboaeat_db
      - spring.datasource.username=postgres
      - spring.datasource.password=Ee6mSPwjG85W
    networks:
      mboa-network:
          aliases:
            - customer-api-net
      postgres-net:
          aliases:
            - postgres
  order-api:
    image: eu.gcr.io/voltaic-cocoa-280715/order-repository
    environment:
      - spring.cloud.consul.host=consul-node1
      - spring.datasource.url=jdbc:postgresql://34.66.68.210:5432/mboaeat_db
      - spring.datasource.username=postgres
      - spring.datasource.password=Ee6mSPwjG85W
    networks:
      mboa-network:
        aliases:
          - order-api-net
      postgres-net:
        aliases:
          - postgres

  gateway-service:
    image: eu.gcr.io/voltaic-cocoa-280715/gateway-repository
    environment:
      - spring.cloud.consul.host=consul-node1
    ports:
    - 7000:7000
    networks:
      mboa-network:
        aliases:
          - gateway-service-net
      postgres-net:
        aliases:
          - postgres

volumes:
  consul-node1_data:
    driver: local
  consul-node2_data:
    driver: local
  consul-node3_data:
    driver: local

networks:
  postgres-net:
    external: true
  mboa-network:
    name: mboa-network