version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-mboaeat_db}
      PGDATA: /user/local/postgres_data
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      -   /Users/moussisalomon/dev/volumes/postgres:/user/local/postgres_data
     # - type: volume
     #   source: postgres_data
     #   target: /user/local/postgres_data
    ports:
      - "5432:5432"
    networks:
      postgres-net:
        aliases:
          - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      #SCRIPT_NAME:  /pgadmin4 2z7rICEOwlcrhaKv Ee6mSPwjG85W
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "80:80"
    networks:
      postgres-net:
        aliases:
          - pgadmin-net

networks:
  postgres-net:
    name: postgres-net


volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local